---
- name: Install apache
  hosts: 192.168.33.10
  tasks:
    - name: Task 1
      apt:
        name: apache2
        state: present
        update_cache: yes
        force_apt_get: yes
        autoclean: yes
        autoremove: yes
  
